### ISSUE TITLE
fake

### ISSUE THREAD

**Issue by shekhar-patle** [Open-Security-Group-OSG/HiddenEyeReborn#32]

**Comment by Morsmalleo** [comment]
No its not fake mate, its still in development, give the developer a break before you start calling his work fake please, maybe try and contact the developer next time before accusing him of making fake open source projects, I don't care when your issue was posted either, have some respect for other peoples work whether it be finished or still in development

**Comment by darkmidus** [comment]
@Morsmalleo Its strange having people take up for the dev's, doesn't happen often

**Comment by Morsmalleo** [comment]
> @Morsmalleo Its strange having people take up for the dev's, doesn't happen often

Yes I have noticed that quite a bit myself, I believe simply that if someone needs help, and ASKS FOR IT nicely like the dev of HE:RE did, you should give it to them if YOU ARE able to help in the areas they need help in, if you can't help simply share it to someone you do know that can help if they dev would allow that, and after seeing how well HiddenEye performed, I needed to help bring this project to life, I even used HiddenEye to recover a stolen Facebook account for one my friends hence why I love it so much, its a beautiful thing if used in the right hands

**Comment by sTiKyt** [comment]
Duplicate of #11
