### ISSUE TITLE
Pathetic 

### ISSUE THREAD

**Issue by PrivyetCyka** [Open-Security-Group-OSG/HiddenEyeReborn#59]
What a fucking loser ... You think you're the shit because you wrote a program that for all anyone knows doesn't even work...what kind of neckbeard overinflated little dick energy beta cuck boy makes a program available and then gets mad because people want to know how to use it...  If we play by your rules and read the other issues you can clearly tell some people have been able to run it .. you had one fucking job..one..b stop sucking your own little ass dick and thinking you're cool

**Comment by sTiKyt** [comment]
@PrivyetCyka

**Comment by sTiKyt** [comment]
Lmfao, imagine being able to run something that virtually has no fucking code... Jeez you don't know what versioning is? Do you? Ok, let's see what it says..
![image](https://user-images.githubusercontent.com/35602029/130358484-5f751fb0-a34f-4464-8ef3-0cc98c9f86de.png)

**Comment by sTiKyt** [comment]
> You think you're the shit because you wrote a program doesn't even work 

This one is funny, because it does exactly what I need it to do,

> you had one fucking job..one..b"

Well, no I didn't... this is open-source, I'm not paid nor donated any money, I have no other devs relying on me, I have no reason to develop this except my own wish,  I do it because it's MY HOBBY. Not because someone wants something... You have no vote in this dude...

**Comment by sTiKyt** [comment]
Anyway, I would like no notice you are aggressive trash, and we don't need that here, have your ban. I hope you can chill someday and stop attacking random devs on internet...
